### ISSUE TITLE
Visual bugs with reflections and blocks.

### ISSUE THREAD

**Issue by TotalBodan** [GeForceLegend/SEUS_PTGI_GFME#49] opened 2024-12-11 12:04 UTC
System: ryzen 5 5500, Rx 6750xt 12gb, 32 gb ram, fabric mods: Sodium, iris 1.21.1, rotrBLOCKS have visual bugs on blocks with Seus ptgi gfme 1.17) glitched reflections, screenshots from ptgi_gfme 1.17.
![2024-12-11_14 53 11](https://github.com/user-attachments/assets/b9c2c686-8ba4-4865-9464-1ff274766e26)
![2024-12-11_15 10 53](https://github.com/user-attachments/assets/7a6a16ac-0a1a-42b3-8582-873eff39deb1)

**Comment by TotalBodan** [comment] 2024-12-11 13:47
I tested it on both similar result.

**Comment by GeForceLegend** [comment] 2024-12-11 14:17
Normally it will be caused by inconsistent texture size in resource packs, which may result in block/item atlas texture not ordered as expected, tho looks a bit different from common scene. Almost nothing I can do here, you can try rescale textures with inconsistent size to the same.

**Comment by TotalBodan** [comment] 2024-12-11 14:22
I have all textures same 128x size in rotrblocks and dont have other resourcepacks.

**Comment by GeForceLegend** [comment] 2024-12-11 14:36
Can you press F3+S and send `.minecraft/screenshots/debug/minecraft_textures_atlas_blocks.png_0.png`? I would like to check the atlas texture

**Comment by TotalBodan** [comment] 2024-12-11 14:59
I am understand It's because of pointblank mod others mods is optimisation mods i delete it and everything is good.
![2024-12-11_18 53 07](https://github.com/user-attachments/assets/c235ad3c-461c-4632-9235-20be9b87766f)
Old atlas  with pointblank https://drive.google.com/file/d/1OqDv137XsiucEIHX3NDxokeiZYc_Fzrv/view?usp=sharing and new. https://drive.google.com/file/d/1HSKiS-C_NGXkdPtW-Wx5TPHw7w5MmyGr/view?usp=drive_link

**Comment by GeForceLegend** [comment] 2024-12-11 15:02
If everything can be good, I'll close this issue then.

**Closed by GeForceLegend** 2024-12-11 15:02 UTC
